const GroundItems = {
  concrete: {
    name: 'concrete',
    canBeDug: false,
    hardiness: null,
    canBeExploded: false,
    damage: null,
    price: null,
    instantCash: false,
  },
  grass: {
    name: 'grass',
    canBeDug: true,
    hardiness: 0.9,
    canBeExploded: true,
    damage: null,
    price: null,
    instantCash: false,
  },
  ground: {
    name: 'ground',
    canBeDug: true,
    hardiness: 0.9,
    canBeExploded: true,
    damage: null,
    price: null,
    instantCash: false,
  },
  groundWithGas: {
    name: 'ground',
    canBeDug: true,
    hardiness: 0.9,
    canBeExploded: true,
    damage: 10,
    price: null,
    instantCash: false,
  },
  rock: {
    name: 'rock',
    canBeDug: false,
    hardiness: null,
    canBeExploded: true,
    damage: null,
    price: null,
    instantCash: false,
  },
  lava: {
    name: 'lava',
    canBeDug: true,
    hardiness: 2.8,
    canBeExploded: true,
    damage: 20,
    price: null,
    instantCash: false,
  },
  ironium: {
    name: 'ironium',
    canBeDug: true,
    hardiness: 1.3,
    canBeExploded: true,
    damage: null,
    price: 30,
    instantCash: false,
  },
  bronzium: {
    name: 'bronzium',
    canBeDug: true,
    hardiness: 1.8,
    canBeExploded: true,
    damage: null,
    price: 60,
    instantCash: false,
  },
  silverium: {
    name: 'silverium',
    canBeDug: true,
    hardiness: 2.3,
    canBeExploded: true,
    damage: null,
    price: 100,
    instantCash: false,
  },
  goldium: {
    name: 'goldium',
    canBeDug: true,
    hardiness: 2.8,
    canBeExploded: true,
    damage: null,
    price: 250,
    instantCash: false,
  },
  platinium: {
    name: 'platinium',
    canBeDug: true,
    hardiness: 3.3,
    canBeExploded: true,
    damage: null,
    price: 750,
    instantCash: false,
  },
  einsteinium: {
    name: 'einsteinium',
    canBeDug: true,
    hardiness: 3.8,
    canBeExploded: true,
    damage: null,
    price: 2000,
    instantCash: false,
  },
  emerald: {
    name: 'emerald',
    canBeDug: true,
    hardiness: 4.3,
    canBeExploded: true,
    damage: null,
    price: 5000,
    instantCash: false,
  },
  ruby: {
    name: 'ruby',
    canBeDug: true,
    hardiness: 4.8,
    canBeExploded: true,
    damage: null,
    price: 20000,
    instantCash: false,
  },
  diamond: {
    name: 'diamond',
    canBeDug: true,
    hardiness: 5.3,
    canBeExploded: true,
    damage: null,
    price: 100000,
    instantCash: false,
  },
  amazonite: {
    name: 'amazonite',
    canBeDug: true,
    hardiness: 5.8,
    canBeExploded: true,
    damage: null,
    price: 100000,
    instantCash: false,
  },
  dinosaurBones: {
    name: 'dinosaur_bones',
    canBeDug: true,
    hardiness: 1.8,
    canBeExploded: true,
    damage: null,
    price: 1000,
    instantCash: true,
  },
  treasure: {
    name: 'treasure',
    canBeDug: true,
    hardiness: 1.8,
    canBeExploded: true,
    damage: null,
    price: 5000,
    instantCash: true,
  },
  martianSkeleton: {
    name: 'martian_skeleton',
    canBeDug: true,
    hardiness: 1.8,
    canBeExploded: true,
    damage: null,
    price: 10000,
    instantCash: true,
  },
  religiousArtifact: {
    name: 'religious_artifact',
    canBeDug: true,
    hardiness: 1.8,
    canBeExploded: true,
    damage: null,
    price: 10000,
    instantCash: true,
  },
}

export default GroundItems
